spring:
  application:
    name: sturdy-fernacular
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/tickets}
    username: ${SPRING_DATASOURCE_USERNAME:tickets}
    password: ${SPRING_DATASOURCE_PASSWORD:}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
